version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/mongodb"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/mysql"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/sqlite"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
